### ISSUE TITLE
single-key-description function returns different results comparing to one in regular Emacs

### ISSUE THREAD

**Issue by antonyshchenko** [aquamacs-emacs/aquamacs-emacs#101]
For example:

`(single-key-description 115)`

in Aquamacs will return "S", while in Emacs it returns "s". What could cause this?

Smartparens mode relies heavily on single-key-description and this difference in behaviour makes this mode unusable.

**Comment by antonyshchenko** [comment]
After some further investigation I found out that function behaves as expected if I turn off `ns-use-mac-modifier-symbols` setting. Also I can see this in the code: https://github.com/davidswelt/aquamacs-emacs/blob/18e8c5dc1de401a1f000b2f88909359dac82de44/src/keymap.c#L2368

I wonder if it's a bug or a feature and why it is like this.

**Comment by davidswelt** [comment]
That's most certainly a feature.  
You should report this to the smartparens package.  I found, in its code:  "If the last command the event as described by `single-key-description' matches any on the list, the hook will be executed."
So, the package makes assumptions about what a key description looks like, and that is obviously incompatible (and a hack on their part).

Closing this, as it is probably not an Aquamacs bug, but a smartparens one.

**Comment by Fuco1** [comment]
Why is it a feature that it upcases the event code's string representation? 115 is lower case s.

**Comment by davidswelt** [comment]
It’s not just a string representation.  As documented, it returns a "pretty description”, which means, it returns something that is displayed to the user.

It does that because, at least on the Mac, key descriptions (e.g.,  in menus) are upper case.

The mode should not be parsing the UI level representations.

For more complex event codes, that would be a different story, and if it does that (I didn’t check just now), we could change that.

**Comment by Fuco1** [comment]
Since upper case and lower case events are _different_ in emacs, this still sounds like an anti-feature.

I agree that the usage in SP is a hack, but so is half of emacs ;)  I'll make myself a todo to change these to something more portable.
