### ISSUE TITLE
Emacsclient opens a new frame even without the -c option if aquamacs is in a different workspace

### ISSUE THREAD

**Issue by fakedrake** [aquamacs-emacs/aquamacs-emacs#102]
I tried `(setq server-log t)` and ran `emacsclient /tmp/test.md`. On `*server*`

```
Sat Oct 24 15:50:55 2015 server <1>: Status changed to open: open from -
Sat Oct 24 15:50:55 2015 server <1>: server-delete-client
Sat Oct 24 15:50:55 2015 server <1>: Received -dir /usr/bin/ -current-frame -tty /dev/ttys002 screen-256color -file /tmp/test.md 
Sat Oct 24 15:50:55 2015 server <1>: Sent -emacs-pid 98780
Sat Oct 24 15:50:55 2015 server <1>: New file: /tmp/test.md 
```

But a new window still appears. The following might also be helpful to spotting the issue:
- If aquamacs is on the same workspace as the terminal invoking emacsclient, the behavior is normal: the aquamacs frame gets focused with the requested file in the selected buffer.
- `edebug-defun`ing any server.el functions makes it impossible to reproduce the problem since if an aquamacs's frame is already selected, sever uses that frame as it should.
- `(setq server-window (car (frame-list))` didn't help (btw why is `(frame-list)` evaluating to 3 frames when one is open?)
- `one-buffer-one-frame` mode is disabled and doesn't seem to be the problem.
- The window `default` face's `:background` and `:foreground`  were reset to default in the created frame (bg white, fg black). Other faces are as expected. This however most probably has to do with all frame creations and is a separate issue.
- I am on OS X yosemite

**Comment by davidswelt** [comment]
(frame-list) will show all live frames, including hidden ones.

**Comment by davidswelt** [comment]
The current behavior means that if there is no frame visible in the current workspace, one is created to accommodate the new window/buffer.

What is the behavior you would find more appropriate?  Switching to a workspace that has the selected frame, and using that?

**Comment by itollefsen** [comment]
I think I'm seeing the same issue.

I've got Aquamacs pinned to one (of four) spaces and I'm using the desktop save/restore feature.

When I start Aquamacs and it starts loading buffers (lazy loading), I might switch to another space to check e-mail for instance. Aquamacs will then bring me back to the original space and open a new frame on top of the old one.

I wondered why that was, but the issue described here makes sense of it. It's actually trying to open a new frame in the space I'm in, but since I've got it pinned to space it first switches to that space, resulting in a new frame on top of the original one.

> What is the behavior you would find more appropriate? Switching to a workspace that has the selected frame, and using that?

Yes, that would be my preference.

For the situation I described, it would be even better if it didn't switch spaces, but just opened the buffer in the existing frame regardless. However, that's only appropriate for lazy loading a desktop and would otherwise not be what you'd expect. So I'd rather have it switch space and use the existing frame, even for lazy loading.

**Comment by laserscout** [comment]
I think I have devised a simple and elegant solution...
https://gist.github.com/laserscout/38268fe2b773bb5b69157679c5d230b0

**Comment by treese** [comment]
With Aquamacs 3.5 on Mojave, I have the following:

1. Aquamacs pinned in one workspace
2. Switch to a different workspace
3. From a terminal window in the new workspace, run `/Applications/Aquamacs.app/Contents/MacOS/bin/emacsclient /tmp/foo.txt`
4. This switches to the workspace with Aquamacs and opens the file in my existing frame.

Which I think is what was described above as the desired behavior.

Since this is a bit old, I'm going to go ahead and close it, but if I missed something, please reopen the issue.

**Comment by itollefsen** [comment]
I did manage to solve this so it behaved the way I wanted it to (lazy loading did not switch desktop). Unfortunately, I have forgotten exactly what I did that fixed it. I'll jolt down the settings that I _think_ did the trick, in case someone comes searching for clues:
```
(custom-set-variables
  '(pop-up-frames nil)
  '(pop-up-frame-function nil)
  '(display-buffer-reuse-frames nil)
  '(display-buffer-alist (append display-buffer-alist '((reusable-frames . nil))))
  '(display-buffer-base-action
    '((display-buffer-reuse-window
       display-buffer-in-previous-window
       display-buffer-use-some-window))))
```

**Comment by treese** [comment]
@itollefsen Thanks for adding your solution!
