### ISSUE TITLE
Aquamacs defaults for AUCTeX not configurable

### ISSUE THREAD

**Issue by braunm** [aquamacs-emacs/aquamacs-emacs#217]
Example: Suppose  I want to turn off `TeX-parse-self` through Customize. I go to the TeX Parse customize group and toggle TeX Parse Self to off (nil). I save for future sessions, and restart Aquamacs.  I confirm that `'(TeX-parse-self nil)` is in my customizations.el file.  But Aquamacs is still self-parsing. Back to Customize, I see that TeX-parse-self is back to on (t), with a message CHANGED outside Customize.   

So why won't this setting stick?  I've traced the problem back to `aquamacs/src/site-list/edit-modes/auctex-config.el,` and the call to `aquamacs-set-defaults` at line 57.  This same problem occurs for all 7 of the variables that are set there, like `reftex-save-parse-info` and `reftex-plug-into-AUCTeX`.  So by setting Aquamacs defaults in this way, it appears to make it impossible to customize them the way AUCTeX intends.

A workaround is to put `(set TeX-parse-self nil)` in my `emacs-startup-hook`.  But I really should not have to do that.  If Aquamacs sets defaults for custom variables, shouldn't those variables remain customizable?

Possible relevant notes:

1. I do not know if this is a 3.6beta thing.  I never tried this before.
2. This is also the file where  the default for `TeX-view-program-list` is set, and I see that "Preview" is listed before "Skim" in that list (line 262).  Could that be related to issue  #216 ?

**Comment by treese** [comment]
@braunm Nice catch! This is a new bug in the beta, and it's not how things worked in 3.5. It's caused by the changes I made in an attempt to make loading a newer version of AUCTeX through `list-packages` work better. I think I will end up backing out that change for now, because getting the initialization flow right looks a little tricky (and trickier than I originally thought). 

I suspect you are right about this being the underlying cause of #216, so I definitely appreciate the help in figuring that one out.

**Comment by treese** [comment]
I backed out the AUCTeX loading change for 3.6, so this shouldn't be a problem for now. An updated beta build will be available shortly.
