### ISSUE TITLE
High memory for aquamacs 3.6 beta

### ISSUE THREAD

**Issue by acmaggs** [aquamacs-emacs/aquamacs-emacs#223]
I have had a couple of occasions when the aquamacs 3.6 beta has started using large amounts of memory, above 800MB. I have never seen this with the stable 3.5. I am using aquamacs to edit moderate size (20 page) latex documents using auctex. The document stays open for weeks and is regularly modified and/or updated from git.

Is there a way to debug/find why this is happening?

**Comment by treese** [comment]
Thanks for the port. Are you using an M1 or x86 system?

I've seen this also, and tracking it down is the major holdup for releasing an updated beta version. I've made some progress, but there's still at least one leak I haven't found yet.

**Comment by acmaggs** [comment]
This is an old macbook air. 1,3 GHz Dual-Core Intel Core i5

**Comment by treese** [comment]
Thanks for letting me know. I haven't seen it much on my x86 MacBook, but it's definitely happening on my M1 system, so I wanted to see if that was a relevant difference.

**Comment by treese** [comment]
I think I introduced this problem in trying to fix some other memory issues. I backed out those changes, and I think it's working better for beta 2. If you notice it happening when beta 2 or the full 3.6 release is out, please reopen this.

**Comment by seh** [comment]
Thank you, Win. I've been finding that Activity Monitor reports Aquamacs using as much as 16 GB of RAM before I finally kill it and restart it. I suspect that it's this large memory allocation that makes modes like _magit_ so slow lately; it takes longer to spawn helper tools like _git_, perhaps due to some _fork_/_exec_ action needing to clone that address space first.
