### ISSUE TITLE
E.T.A. for Aquamacs 4?

### ISSUE THREAD

**Issue by marcoxa** [aquamacs-emacs/aquamacs-emacs#238]
Hi

I know it is a not-so-smart question to ask, but is there an E.T.A. for Aquamacs 4.x?

I am experiencing a bit of bit rot in some of my elisp packages, which used to load, but don't anymore after updating them.  Obviously they want a 27.x or later "base Emacs".

Thanks

Marco

**Comment by treese** [comment]
This is a fine question to ask! From the outside, it looks like not much is happening with Aquamacs.

Behind the scenes, I'm working on a giant merge of the source code to get Aquamacs up to Emacs 28. There are many, many, many changes since Aquamacs was last merged up to Emacs 25, and it's a slow process.

There's a decent chance it's out by the end of the year, but like driving down a winding road in the fog: it's hard to see how much trouble might be up ahead!

**Comment by marcoxa** [comment]
Thank you.  I was sure things were moving on your side.  I just wanted reassurances :)

All the best

Marco

**Comment by rpgoldman** [comment]
If there is anything we can do to help, please announce!
