### ISSUE TITLE
aqumacs24 fails to built on MacOS 10.8

### ISSUE THREAD

**Issue by avaranovich** [aquamacs-emacs/aquamacs-emacs#71]
Hi,

I am on mac os 10.8 and trying to build the aqumacs24 branch.

./autogen/copy_autogen
./configure --with-ns
make install

gives me:
....
checking for nlink_t... yes
checking whether localtime_r is declared... yes
checking whether localtime_r is compatible with its POSIX signature... yes
checking whether stat handles trailing slashes on directories... yes
checking whether stat handles trailing slashes on files... no
./configure: line 24152: syntax error near unexpected token `fi'
./configure: line 24152:`  fi'

**Comment by davidswelt** [comment]
Andrei,

I have a committed a change that should take care of this problem.
It went unnoticed because I (and probably most people building it) have GNU Autotools installed. Thanks for letting me know about it.
- David

## 

http://aquamacs.org -- Aquamacs: Emacs on Mac OS X
http://aquamacs.org/donate -- Could we help you? Return the favor and support the Aquamacs Project!

**Comment by avaranovich** [comment]
David, thanks for the quick fix! Works now.
